# Generated by Django 4.2 on 2023-04-11 18:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='iframe',
            field=models.TextField(default='<IFRAME SRC="https://uqload.co/embed-xxe5frf09hqv.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>'),
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='film',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='imagecaptions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='biographie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
